package view;

/**
 * Represents a ViewEvent
 */
public enum ViewEvent {
  BLUR, BRIGHTEN, FOCUSBLUE, FOCUSGREEN, FOCUSINTENSITY, FOCUSLUMA, FOCUSRED, FOCUSVALUE,
  GREYSCALE, HORIZONTALFLIP, VERTICALFLIP, SAVE, LOAD, SEPIA, SHARPEN, FOCUS;
}
